
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
dotenv.config();

export default {
  databaseUrl: process.env.DATABASE_URL
};
